# Copyright 2020 Adam Chalkley
#
# https://github.com/atc0005/go-ci
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.

# https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for Go modules
  - package-ecosystem: "gomod"

    # Look for a `go.mod` file in the `root` directory
    directory: "/tools"

    # Default is a maximum of five pull requests for version updates
    open-pull-requests-limit: 10

    target-branch: "master"

    # Daily update checks; default version checks are performed at 05:00 UTC
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "America/Chicago"

    # Assign everything to me by default
    assignees:
      - "atc0005"
    labels:
      - "dependencies"

    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "direct"

    commit-message:
      # Prefix all commit messages with "go.mod"
      prefix: "go.mod"

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 10
    target-branch: "master"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "America/Chicago"
    assignees:
      - "atc0005"
    labels:
      - "dependencies"
      - "CI"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "ghaw"

  - package-ecosystem: docker
    directory: "/oldstable/build/release"
    open-pull-requests-limit: 10
    target-branch: "master"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "America/Chicago"

    # Ignore updates from series associated with "stable" container image and
    # no longer supported Go versions.
    ignore:
      - dependency-name: "golang"
        versions:
          # Greater than or equal to stable container image series
          - ">= 1.21"

          # Less than oldstable series
          - "< 1.20"
    assignees:
      - "atc0005"
    labels:
      - "dependencies"
      - "CI"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "docker"

  - package-ecosystem: docker
    directory: "/oldstable/combined"
    open-pull-requests-limit: 10
    target-branch: "master"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "America/Chicago"

    # Ignore updates from series associated with "stable" container image and
    # no longer supported Go versions.
    ignore:
      - dependency-name: "golang"
        versions:
          # Greater than or equal to stable container image series
          - ">= 1.21"

          # Less than oldstable series
          - "< 1.20"
    assignees:
      - "atc0005"
    labels:
      - "dependencies"
      - "CI"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "docker"

  - package-ecosystem: docker
    directory: "/oldstable/build/alpine-x64"
    open-pull-requests-limit: 10
    target-branch: "master"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "America/Chicago"
    assignees:
      - "atc0005"
    labels:
      - "dependencies"
      - "CI"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "docker"
    ignore:
      - dependency-name: "golang"
        versions:
          # Greater than or equal to stable container image series
          - ">= 1.21"

          # Less than oldstable series
          - "< 1.20"

  - package-ecosystem: docker
    directory: "/oldstable/build/alpine-x86"
    open-pull-requests-limit: 10
    target-branch: "master"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "America/Chicago"
    assignees:
      - "atc0005"
    labels:
      - "dependencies"
      - "CI"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "docker"
    ignore:
      - dependency-name: "i386/golang"
        versions:
          # Greater than or equal to stable container image series
          - ">= 1.21"

          # Less than oldstable series
          - "< 1.20"

  - package-ecosystem: docker
    directory: "/stable/combined"
    open-pull-requests-limit: 10
    target-branch: "master"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "America/Chicago"
    assignees:
      - "atc0005"
    labels:
      - "dependencies"
      - "CI"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "docker"
    ignore:
      - dependency-name: "golang"
        versions:
          - ">= 1.22"
          - "< 1.21"

  - package-ecosystem: docker
    directory: "/stable/build/alpine-x64"
    open-pull-requests-limit: 10
    target-branch: "master"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "America/Chicago"
    assignees:
      - "atc0005"
    labels:
      - "dependencies"
      - "CI"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "docker"
    ignore:
      - dependency-name: "golang"
        versions:
          - ">= 1.22"
          - "< 1.21"

  - package-ecosystem: docker
    directory: "/stable/build/alpine-x86"
    open-pull-requests-limit: 10
    target-branch: "master"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "America/Chicago"
    assignees:
      - "atc0005"
    labels:
      - "dependencies"
      - "CI"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "docker"
    ignore:
      - dependency-name: "i386/golang"
        versions:
          - ">= 1.22"
          - "< 1.21"

  - package-ecosystem: docker
    directory: "/unstable/build/alpine-x64"
    open-pull-requests-limit: 10
    target-branch: "master"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "America/Chicago"
    assignees:
      - "atc0005"
    labels:
      - "dependencies"
      - "CI"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "docker"

  - package-ecosystem: docker
    directory: "/unstable/build/alpine-x86"
    open-pull-requests-limit: 10
    target-branch: "master"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "America/Chicago"
    assignees:
      - "atc0005"
    labels:
      - "dependencies"
      - "CI"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "docker"

  - package-ecosystem: docker
    directory: "/stable/build/cgo-mingw-w64"
    open-pull-requests-limit: 10
    target-branch: "master"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "America/Chicago"
    assignees:
      - "atc0005"
    labels:
      - "dependencies"
      - "CI"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "docker"
    ignore:
      - dependency-name: "golang"
        versions:
          - ">= 1.22"
          - "< 1.21"

  - package-ecosystem: docker
    directory: "/stable/build/release"
    open-pull-requests-limit: 10
    target-branch: "master"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "America/Chicago"
    assignees:
      - "atc0005"
    labels:
      - "dependencies"
      - "CI"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "docker"
    ignore:
      - dependency-name: "golang"
        versions:
          - ">= 1.22"
          - "< 1.21"

  - package-ecosystem: docker
    directory: "/mirror/1.19"
    open-pull-requests-limit: 10
    target-branch: "master"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "America/Chicago"
    assignees:
      - "atc0005"
    labels:
      - "dependencies"
      - "CI"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "docker"
    ignore:
      - dependency-name: "golang"
        versions:
          - ">= 1.20"
          - "< 1.19"

  - package-ecosystem: docker
    directory: "/mirror/1.20"
    open-pull-requests-limit: 10
    target-branch: "master"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "America/Chicago"
    assignees:
      - "atc0005"
    labels:
      - "dependencies"
      - "CI"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "docker"
    ignore:
      - dependency-name: "golang"
        versions:
          - ">= 1.22"
          - "< 1.21"

  - package-ecosystem: docker
    directory: "/unstable/build/release"
    open-pull-requests-limit: 10
    target-branch: "master"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "America/Chicago"
    assignees:
      - "atc0005"
    labels:
      - "dependencies"
      - "CI"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "docker"

  - package-ecosystem: docker
    directory: "/unstable/combined"
    open-pull-requests-limit: 10
    target-branch: "master"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "America/Chicago"
    assignees:
      - "atc0005"
    labels:
      - "dependencies"
      - "CI"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "docker"
