# Copyright 2020 Adam Chalkley
#
# https://github.com/atc0005/go-ci
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.

issues:
  # equivalent CLI flag: --exclude-use-default
  #
  # see:
  #   atc0005/todo#22
  #   atc0005/todo#29
  #   golangci-lint/golangci-lint#1249
  #   golangci-lint/golangci-lint#413
  exclude-use-default: false

# run:
# Define the Go version limit.
# Mainly related to generics support in go1.18.
# Default: use Go version from the go.mod file, fallback on the env var `GOVERSION`, fallback on 1.18
# https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml
# go: "1.19"

# Reminder: Sort this after every change
linters:
  enable:
    # https://github.com/atc0005/go-ci/issues/1024
    # - depguard
    - dogsled
    - dupl
    - exportloopref
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gosec
    - govet
    - misspell
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - unconvert

#
# Disable govet:fieldalignment, re-enable deprecated maligned linter until the
# Go team offers more control over the types of checks provided by the
# fieldalignment linter or golangci-lint does so.
#
# See https://github.com/atc0005/go-ci/issues/302 for more information.
#
# disable:
#   - maligned

linters-settings:
  govet:
    # Wait until after Go 1.19 is out and/or I have sufficient time to update
    # projects dependent on these containers.
    #
    # See also:
    #
    # https://github.com/atc0005/go-ci/issues/666
    #
    # enable-all: true
    disable:
      #
      # Disable fieldalignment settings until the Go team offers more control over
      # the types of checks provided by the fieldalignment linter or golangci-lint
      # does so.
      #
      # See https://github.com/atc0005/go-ci/issues/302 for more information.
      #
      - fieldalignment
