# Copyright 2025 Adam Chalkley
#
# https://github.com/atc0005/go-ci
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.

version: "2"
linters:
  enable:
    - copyloopvar
    - dogsled
    - dupl
    - goconst
    - gocritic
    - gosec
    - misspell
    - prealloc
    - revive
    - staticcheck
    - unconvert
  settings:
    govet:
      disable:
        #
        # Disable fieldalignment settings until the Go team offers more control over
        # the types of checks provided by the fieldalignment linter or golangci-lint
        # does so.
        #
        # See https://github.com/atc0005/go-ci/issues/302 for more information.
        #
        - fieldalignment
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
