# Copyright 2020 Adam Chalkley
#
# https://github.com/atc0005/go-ci
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.

###############################################################################
# NOTE: This is the golangci-lint configuration file *specific* to the
# "unstable" variant of the container images provided by this project. This
# configuration (potentially) enables additional linters not used by the other
# container image variants.
###############################################################################

issues:
  # equivalent CLI flag: --exclude-use-default
  #
  # see:
  #   atc0005/todo#22
  #   atc0005/todo#29
  #   golangci-lint/golangci-lint#1249
  #   golangci-lint/golangci-lint#413
  exclude-use-default: false

# run:
# Define the Go version limit.
# Mainly related to generics support in go1.18.
# Default: use Go version from the go.mod file, fallback on the env var `GOVERSION`, fallback on 1.18
# https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml
# go: "1.19"

# Reminder: Sort this after every change
linters:
  enable:
    # https://github.com/atc0005/go-ci/issues/1024
    # - depguard
    - dogsled
    - dupl
    - err113
    - errcheck
    - copyloopvar
    - gochecknoglobals
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - govet
    - misspell
    - nilnil
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - unconvert

#
# Disable govet:fieldalignment, re-enable deprecated maligned linter until the
# Go team offers more control over the types of checks provided by the
# fieldalignment linter or golangci-lint does so.
#
# See https://github.com/atc0005/go-ci/issues/302 for more information.
#
# disable:
#   - maligned

linters-settings:
  gocognit:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 10

  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 15

  govet:
    enable-all: true
    disable:
      #
      # Disable fieldalignment settings until the Go team offers more control over
      # the types of checks provided by the fieldalignment linter or golangci-lint
      # does so.
      #
      # See https://github.com/atc0005/go-ci/issues/302 for more information.
      #
      - fieldalignment
