# Copyright 2025 Adam Chalkley
#
# https://github.com/atc0005/go-ci
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.

###############################################################################
# NOTE: This is the golangci-lint configuration file *specific* to the
# "unstable" variant of the container images provided by this project. This
# configuration (potentially) enables additional linters not used by the other
# container image variants.
###############################################################################

version: "2"
linters:
  enable:
    - copyloopvar
    - dogsled
    - dupl
    - err113
    - gochecknoglobals
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - nilnil
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - unconvert
  settings:
    gocognit:
      min-complexity: 10
    gocyclo:
      min-complexity: 15
    govet:
      disable:
        #
        # Disable fieldalignment settings until the Go team offers more control over
        # the types of checks provided by the fieldalignment linter or golangci-lint
        # does so.
        #
        # See https://github.com/atc0005/go-ci/issues/302 for more information.
        #
        - fieldalignment
      enable-all: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
